include: package:flutter_lints/flutter.yaml

linter:
  rules:
     prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
     file_names: false  # Disable file name rules

analyzer:
  plugins:
    - custom_lint